services:
  - type: web
    name: dl-extractor
    env: node
    buildCommand: cd frontend && NODE_ENV=development npm install && npm run build && cd ../backend && NODE_ENV=development npm install && npx playwright install chromium && npm run build
    startCommand: cd backend && node dist/index.js
    envVars:
      - key: NODE_ENV
        value: production
